parallel: true
plugins:
  - standard-rails
  - standard-performance
ignore:
  - "config/deploy.rb":
      - Rails/Exit
  - "**/*":
      - Rails/HasAndBelongsToMany
  - db/migrate/2022*
  - db/migrate/2021*
  - db/migrate/2020*
  - db/migrate/201*
  - db/migrate/2023*
  - db/migrate/2024*
