 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/collection/:id/time_spans", type: :request do

  # TimeSpan. As you add validations to TimeSpan, be sure to
  # adjust the attributes here as well.
  let(:collection) {
    collections(:collection1)
  }

  let(:valid_attributes) {
    {
      subject_id: works(:work1).id,
      subject_type: "Work",
      collection_id: collection.id,
      status: "concept",
      classification: "rental_outgoing"
    }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TimeSpan.create! valid_attributes
      get collection_time_spans_url(collection)
      expect(response).to be_redirect
    end
    it "renders a successful response" do
      sign_in users(:admin)

      TimeSpan.create! valid_attributes
      get collection_time_spans_url(collection)
      expect(response).to be_successful
    end

    it "renders a not authorized response" do
      sign_in users(:advisor)

      TimeSpan.create! valid_attributes
      get collection_time_spans_url(collection)
      expect(response).to be_redirect

    end
  end

  # describe "GET /show" do
  #   it "renders a successful response" do
  #     sign_in users(:admin)
  #     time_span = TimeSpan.create! valid_attributes
  #     get collection_time_span_url(collection, time_span)
  #     expect(response).to be_successful
  #   end
  # end
  #
  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_time_span_url
  #     expect(response).to be_successful
  #   end
  # end
  #
  # describe "GET /edit" do
  #   it "render a successful response" do
  #     time_span = TimeSpan.create! valid_attributes
  #     get edit_time_span_url(time_span)
  #     expect(response).to be_successful
  #   end
  # end
  #
  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new TimeSpan" do
  #       expect {
  #         post time_spans_url, params: { time_span: valid_attributes }
  #       }.to change(TimeSpan, :count).by(1)
  #     end
  #
  #     it "redirects to the created time_span" do
  #       post time_spans_url, params: { time_span: valid_attributes }
  #       expect(response).to redirect_to(time_span_url(TimeSpan.last))
  #     end
  #   end
  #
  #   context "with invalid parameters" do
  #     it "does not create a new TimeSpan" do
  #       expect {
  #         post time_spans_url, params: { time_span: invalid_attributes }
  #       }.to change(TimeSpan, :count).by(0)
  #     end
  #
  #     it "renders a successful response (i.e. to display the 'new' template)" do
  #       post time_spans_url, params: { time_span: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end
  #
  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }
  #
  #     it "updates the requested time_span" do
  #       time_span = TimeSpan.create! valid_attributes
  #       patch time_span_url(time_span), params: { time_span: new_attributes }
  #       time_span.reload
  #       skip("Add assertions for updated state")
  #     end
  #
  #     it "redirects to the time_span" do
  #       time_span = TimeSpan.create! valid_attributes
  #       patch time_span_url(time_span), params: { time_span: new_attributes }
  #       time_span.reload
  #       expect(response).to redirect_to(time_span_url(time_span))
  #     end
  #   end
  #
  #   context "with invalid parameters" do
  #     it "renders a successful response (i.e. to display the 'edit' template)" do
  #       time_span = TimeSpan.create! valid_attributes
  #       patch time_span_url(time_span), params: { time_span: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end
  #
  # describe "DELETE /destroy" do
  #   it "destroys the requested time_span" do
  #     time_span = TimeSpan.create! valid_attributes
  #     expect {
  #       delete time_span_url(time_span)
  #     }.to change(TimeSpan, :count).by(-1)
  #   end
  #
  #   it "redirects to the time_spans list" do
  #     time_span = TimeSpan.create! valid_attributes
  #     delete time_span_url(time_span)
  #     expect(response).to redirect_to(time_spans_url)
  #   end
  # end
end
