require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  describe "GET /users/password/new [QSECIMP0006]" do
    it "is accessible by default (default devise controller)" do
      get new_user_password_path
      expect(response).to be_successful
    end
  end

  describe "GET /users/sign_in" do
    it "uses HTML password fields that hide the passowrd [QSECIMP0012]" do
      get new_user_session_path
      expect(response.body).to match(/input.*type="password" name="user\[password\]" id="user_password"/)
    end
  end

  describe "POST /users/session [QSECIMP0011]" do
    it "returns a 422 when signing in without authenticity token" do
      post user_session_path(params: {user: {email: "test-user2@murb.nl", password: "asdfasdf", remember_me: false}})
      expect(response).to be_unprocessable
    end
  end

  describe "GET /users/:id/edit [QSECIMP0007]" do
    it "is not possible for an anonymous user to edit a user" do
      get edit_user_path(users(:user2))
      expect(response).to be_redirect
    end

    it "is possible for an admin to edit a user" do
      sign_in users(:admin)
      get edit_user_path(users(:user2))
      expect(response).to be_successful
    end

    (User::ROLES - [:admin]).each do |role|
      it "is not possible for an #{role} user to edit a user" do
        sign_in users(role)
        get edit_user_path(users(:user2))
        expect(response).not_to be_successful
      end
    end
  end

  describe "DELETE /users/:id [QSECIMP0007]" do
    it "is not possible for an anonymous user to edit a user" do
      expect do
        delete user_path(users(:user2))
      end.not_to change(User, :count)

      expect(response).to be_redirect
    end

    it "is possible for an admin to edit a user" do
      sign_in users(:admin)
      expect do
        delete user_path(users(:user2))
      end.to change(User, :count).by(-1)
      expect(response).to be_redirect
    end

    (User::ROLES - [:admin]).each do |role|
      it "is not possible for an #{role} user to edit a user" do
        sign_in users(role)
        expect do
          delete user_path(users(:user2))
        end.not_to change(User, :count)
        expect(response).not_to be_successful
      end
    end
  end
end
