files:
  - app/views/layouts/application.html.erb
  - config/locales/branding.en.yml
  - config/locales/branding.nl.yml
  - app/assets/images/logo.svg
  - app/assets/stylesheets/_settings.scss
  - app/assets/stylesheets/variables.scss