# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eed62606adc420addb635ecd2599cb329fae63dbb40a24d09162cb7179be818dff8429a57a5c3e9f3343e9fde655bd2fb89e3e22b3eb31b72fa65b23d1f71121
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  azure_client_id: 5ee084cf-0bea-48b2-83d9-09d5497096b0
  central_login_id: nCxL9EPU0SJnVbpRnGRXAMYv9k8YEchFk9MHkDQJcC8
  central_login_secret: FfEY4uOzERnQfgAP1qGtUez7vTYw4RZTwaIsjr3-3Ig
  central_login_site: "http://localhost:4000/"
  uitleen_site: "http://localhost:5001/"
  from_address: "collectiemanagement@qkunst.nl"

test:
  secret_key_base: 59715fa31149ea55125a542de2973e8ed8d2393d1b97ca1fa9dd538ce30c62b1e5429a57fcf850c1a9e7c17827fca0f42bf35fa7e0e8b3e8c43b53eeec6a80f2
  google_client_id: fake_id
  google_client_secret: fake_secret

gitlab:
  secret_key_base: 59715fa31149ea55125a542de2973e8ed8d2393d1b97ca1fa9dd538ce30c62b1e5429a57fcf850c1a9e7c17827fca0f42bf35fa7e0e8b3e8c43b53eeec6a80f2
  google_client_id: fake_id
  google_client_secret: fake_secret

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  azure_client_id: cd4e2cd4-045b-4460-a109-b78bcc833fed