# https://github.com/mperham/sidekiq/blob/master/examples/config.yml
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
verbose: true
pidfile: ./tmp/pids/sidekiq.pid
concurrency: 2
timeout: 300
default:
  max_retries: 5
queues:
  - [qkunst_often, 7]
  - [qkunst_default, 5]
  - [qkunst_seldom, 3]
schedule:
  schedule_reindex_worker:
    cron: "22 5 * * *"
    class: ScheduleReindexWorkWorker
  schedule_rinse_and_clean:
    cron: "23 5 * * *"
    class: RinseAndCleanWorker
