# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InvolvementsController, type: :controller do
  include Devise::Test::ControllerHelpers

  # This should return the minimal set of attributes required to create a valid
  # Involvement. As you add validations to Involvement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: "a"}
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvolvementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all involvements as @involvements" do
      involvement = Involvement.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to redirect_to(new_user_session_path)
    end
  end

  describe "GET #show" do
    it "assigns the requested involvement as @involvement" do
      involvement = Involvement.create! valid_attributes
      get :show, params: {id: involvement.to_param}, session: valid_session
      expect(response).to redirect_to(new_user_session_path)
    end
  end

  describe "GET #new" do
    it "assigns a new involvement as @involvement" do
      get :new, params: {}, session: valid_session
      expect(response).to redirect_to(new_user_session_path)
    end
  end

  describe "GET #edit" do
    it "assigns the requested involvement as @involvement" do
      involvement = Involvement.create! valid_attributes
      get :edit, params: {id: involvement.to_param}, session: valid_session
      expect(response).to redirect_to(new_user_session_path)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Involvement" do
        expect {
          post :create, params: {involvement: valid_attributes}, session: valid_session
        }.to change(Involvement, :count).by(0)
      end

      it "assigns a newly created involvement as @involvement" do
        post :create, params: {involvement: valid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end

      it "redirects to the created involvement" do
        post :create, params: {involvement: valid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved involvement as @involvement" do
        post :create, params: {involvement: invalid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end

      it "re-renders the 'new' template" do
        post :create, params: {involvement: invalid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "B"}
      }

      it "updates the requested involvement" do
        involvement = Involvement.create! valid_attributes
        put :update, params: {id: involvement.to_param, involvement: new_attributes}, session: valid_session
        involvement.reload
        expect(response).to redirect_to(new_user_session_path)
      end

      it "assigns the requested involvement as @involvement" do
        involvement = Involvement.create! valid_attributes
        put :update, params: {id: involvement.to_param, involvement: valid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end

      it "redirects to the involvement" do
        involvement = Involvement.create! valid_attributes
        put :update, params: {id: involvement.to_param, involvement: valid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    context "with invalid params" do
      it "assigns the involvement as @involvement" do
        involvement = Involvement.create! valid_attributes
        put :update, params: {id: involvement.to_param, involvement: invalid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end

      it "re-renders the 'edit' template" do
        involvement = Involvement.create! valid_attributes
        put :update, params: {id: involvement.to_param, involvement: invalid_attributes}, session: valid_session
        expect(response).to redirect_to(new_user_session_path)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested involvement" do
      involvement = Involvement.create! valid_attributes
      expect {
        delete :destroy, params: {id: involvement.to_param}, session: valid_session
      }.to change(Involvement, :count).by(0)
      expect(response).to redirect_to(new_user_session_path)

    end

    it "redirects to the involvements list" do
      involvement = Involvement.create! valid_attributes
      delete :destroy, params: {id: involvement.to_param}, session: valid_session
      expect(response).to redirect_to(new_user_session_path)
    end
  end

end
